#! /usr/bin/bash

start() {
	sudo service network-manager stop
	sudo /sbin/ifconfig wlan0 up
	sudo /usr/local/bin/hotspotd start	
}

stop() {
	sudo /usr/local/bin/hotspotd stop	
	sudo service network-manager restart
	#iwconfig wlan0 essid $(ESSID)		
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
  *)
  echo "usage $0 start | stop"
esac

