#! /usr/bin/bash

# assume mobile host
mhost() {
	sudo bin/xianet -t -I wlan0 -V -l7 start
} 

# assume fixed host
fhost() {
	sudo bin/xianet -t -I eth0 -V -l7 start
} 

# assume this router runs nameserver and redevous server
gw_router() {
	sudo bin/xianet -rRn -V -l7 start
}

router() {
	sudo bin/xianet -r -V -l7 start
}

stop() {
	sudo bin/xianet stop
}

case "$1" in
	host)
		host
	;;
	gw_router)
		gw_router
	;;
	router)
		router
	;;
	stop)
		stop
	;;	
  *)
  echo "usage $0 host | gw_router | router | stop"
esac

