#! /usr/bin/bash

SRC_MAC_FILTER=**
DST_MAC_FILTER=**

HOST_MAC_FILTER=**

xia_install() {
	sudo apt-get remove wireshark
	sudo apt-get remove wireshark-common
	sudo add-apt-repository ppa:doucette-4/wireshark-xia
	sudo apt-get update
	sudo apt-get install wireshark
}

install() {
	sudo add-apt-repository --remove ppa:doucette-4/wireshark-xia
	sudo apt-get remove wireshark
	sudo apt-get remove wireshark-common
	sudo apt-get update
	sudo apt-get install wireshark
}

# todo: change to tshark; add parameter for interface and MAC
host() {
	#sudo wireshark -i mon0 -f "ether host $HOST_MAC_FILTER" -I
	#sudo wireshark -i wlan0 -f "ether host $HOST_MAC_FILTER" 	
	sudo wireshark -i mon0 -f "ether host $HOST_MAC_FILTER" -p -I -i wlan0 -f "ether host $HOST_MAC_FILTER" 
}

peer() {
	# sudo wireshark -i wlan0 -i mon0 -f "(ether dst $DST_MAC_FILTER and ether src $SRC_MAC_FILTER) or (ether src $DST_MAC_FILTER and ether dst $SRC_MAC_FILTER)" -p -I
	sudo wireshark -i mon0 -f "(ether dst $DST_MAC_FILTER and ether src $SRC_MAC_FILTER) or (ether src $DST_MAC_FILTER and ether dst $SRC_MAC_FILTER)" -p -I # -p no promiscuous mode; -I monitor mode 
}

case "$1" in
	xia_install)
		xia_install
	;;
	install)
		install
	;;
	host)
		host
	;;
	peer)
		peer
	;;	
  *)
  echo "usage $0 host | gw_router | router | stop"
esac
