#! /usr/bin/bash

sudo apt-get update
sudo apt-get install libprotobuf-dev protobuf-compiler openssl libssl-dev python-tk python-dev python-requests swig
sudo apt-get install libzmq3-dev python-zmq python-protobuf python-networkx python-matplotlib

sudo apt-get install make g++
sudo apt-get install doxygen python-sphinx
sudo apt-get install openssh-server
sudo apt-get install git

#git clone https://github.com/XIA-Project/xia-core.git

